/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anagramwords;

import java.awt.Component;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;

/**
 *
 * @author jan
 */
public class AnagramDictionary extends javax.swing.JFrame {

    String dizi[], dizi2[], dizi3[];
    ListHashMap hash;
    int anagram = 0;

    /**
     * Creates new form AnagramDictionary
     */
    public AnagramDictionary() {
        initComponents();
        hash = new ListHashMap(189);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Open File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit to Anagram");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Choose a word :");

        jButton3.setText("Find");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Toplam Anagram Kelime Sayısı:");

        jLabel3.setText("0");

        jLabel4.setText("Algoritma İçin Geçen Süre(ms):");

        jLabel5.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList<String> al = new ArrayList();

        JFileChooser fileChooser = new JFileChooser();
        File file = null;
        Component component = null;
        if (fileChooser.showOpenDialog(component) == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();
        }
        
        BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader(file));
        } catch (FileNotFoundException ex) {
            System.out.println("Dosya yok");
        }
        String s = "";
        try {
            while ((s = br.readLine()) != null) {
                al.add(s);
            }
        } catch (IOException ex) {
            Logger.getLogger(AnagramDictionary.class.getName()).log(Level.SEVERE, null, ex);
        }
        arrayListToString(al);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        long top = 0;
        boolean varMi = true;
        dizi2 = new String[dizi.length];
        for (int i = 0; i < dizi.length; i++) {
            long st = System.nanoTime();
            String s[] = new String[dizi[i].length()];
            for (int j = 0; j < dizi[i].length(); j++) {
                s[j] = dizi[i].substring(j, j + 1);
            }
            insertionSort(s);
            for (int j = 0; j < s.length; j++) {
                dizi2[i] += s[j];
            }
            dizi2[i] = dizi2[i].substring(4);
            dizi2[i] = dizi2[i].trim();
            //System.out.println(dizi2[i]);
            
            hash.put(dizi2[i], dizi[i]);
            
            for (int j = 0; j < jComboBox1.getItemCount(); j++) {
                if (dizi2[i].equals(jComboBox1.getItemAt(j))) {
                    varMi = false;
                    break;
                }
            }
            long fs = System.nanoTime();
            top = top + (fs - st);
                    
            if (varMi) {
                anagram++;
                jComboBox1.addItem(dizi2[i]);
                File file = new File("/home/jan/Desktop/anagram_kelimeler/" + dizi2[i] + ".txt");
                if (!file.exists()) {
                    try {
                        file.createNewFile();
                    } catch (IOException ex) {
                        Logger.getLogger(AnagramDictionary.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                FileWriter fw = null;
                try {
                    fw = new FileWriter(file);
                } catch (IOException ex) {
                    Logger.getLogger(AnagramDictionary.class.getName()).log(Level.SEVERE, null, ex);
                }
                BufferedWriter bw = new BufferedWriter(fw);
                try {
                    bw.write(dizi[i]);
                    bw.newLine();
                } catch (IOException ex) {
                    Logger.getLogger(AnagramDictionary.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    if(bw != null){
                        try {
                            bw.close();
                        } catch (IOException ex) {
                            Logger.getLogger(AnagramDictionary.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    if(fw != null){
                        try {
                            fw.close();
                        } catch (IOException ex) {
                            Logger.getLogger(AnagramDictionary.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            } else {
                File file = new File("/home/jan/Desktop/anagram_kelimeler/" + dizi2[i] +".txt");
                FileWriter fw = null;
                try {
                    fw = new FileWriter(file, true);
                } catch (IOException ex) {
                    Logger.getLogger(AnagramDictionary.class.getName()).log(Level.SEVERE, null, ex);
                }
                BufferedWriter bw = new BufferedWriter(fw);
                try {
                    bw.write(dizi[i]);
                    bw.newLine();
                    bw.close();
                } catch (IOException ex) {
                    Logger.getLogger(AnagramDictionary.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    if(bw != null){
                        try {
                            bw.close();
                        } catch (IOException ex) {
                            Logger.getLogger(AnagramDictionary.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    if(fw != null){
                        try {
                            fw.close();
                        } catch (IOException ex) {
                            Logger.getLogger(AnagramDictionary.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
            varMi = true;
        }
        double ex = top / 1000000.0;
        jLabel3.setText(String.valueOf(anagram));
        jLabel5.setText(String.valueOf(ex));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String s = (String) jComboBox1.getSelectedItem();
        String[] kelimeler = hash.get(s);
        jList1.setListData(kelimeler);
        //YUKARIDAKİ KOD HASHMAP DEN OKUYUP LİSTTE GÖSTERİYOR
        
        /*
        ArrayList<String> al = new ArrayList();
        String s = (String) jComboBox1.getSelectedItem();
        BufferedReader br = null;
        File file = new File("/home/jan/Desktop/anagram_kelimeler/" + s + ".txt");
        try {
            br = new BufferedReader(new FileReader(file));
        } catch (FileNotFoundException ex) {
            System.out.println("Dosya yok");
        }
        String s2 = "";
        try {
            while ((s2 = br.readLine()) != null) {
                al.add(s2);
            }
        } catch (IOException ex) {
            Logger.getLogger(AnagramDictionary.class.getName()).log(Level.SEVERE, null, ex);
        }
        arrayListToString2(al);
        jList1.setListData(dizi3);
        */
        // YUKARIDAKİ KOD DOSYALARDAN OKUYUP LISTTE GÖSTERİYOR
    }//GEN-LAST:event_jButton3ActionPerformed

    void printDizi(String[] dizi) {
        jList1.setListData(dizi);
    }

    void arrayListToString(ArrayList<String> al) {
        dizi = new String[al.size()];
        for (int i = 0; i < al.size(); i++) {
            dizi[i] = al.get(i);
        }
    }

    void arrayListToString2(ArrayList<String> al) {
        dizi3 = new String[al.size()];
        for (int i = 0; i < al.size(); i++) {
            dizi3[i] = al.get(i);
        }
    }

    static void insertionSort(String[] dizi) {
        for (int i = 1; i < dizi.length; i++) {
            int say = i;
            for (int j = i; j >= 0; j--) {
                if (dizi[say].compareTo(dizi[j]) < 0) {
                    String s = dizi[j];
                    dizi[j] = dizi[say];
                    dizi[say] = s;
                    say = say - 1;
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnagramDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnagramDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnagramDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnagramDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnagramDictionary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
